version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Entered the install phase...
      - apt update  > /dev/null
      - npm install -g snyk > /dev/null
      - apt-get install -y maven > /dev/null
      - snyk config set api=$SnykToken
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - snyk monitor --all-projects 
      - echo Snyk test completed on `date`      
      - echo "CodeArtifactRepository is $CodeArtifactRepository"
      - export CODEARTIFACT_URL=$(aws codeartifact get-repository-endpoint --domain $CodeArtifactDomain  --repository $CodeArtifactRepository --format maven --query 'repositoryEndpoint' --output text)
      - echo "CODEARTIFACT_URL is $CODEARTIFACT_URL"
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain $CodeArtifactDomain --query authorizationToken --output text`
      - echo Pre Build completed on `date`
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn -s settings.xml -Dmaven.test.failure.ignore=true clean package deploy > /dev/null
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:  
  files:  
    # - target/*
    - buildspec.yml
